parserOptions:
  ecmaVersion: 2017
  sourceType: module

plugins:
  - prettier

extends:
  - eslint-config-wantora
  - eslint-config-prettier

env:
  es6: true
  browser: true
  commonjs: true
  webextensions: true

globals:
  process: false
  content: false

rules:
  prettier/prettier:
    - warn
    - arrowParens: always
      bracketSpacing: false
      printWidth: 100
      trailingComma: es5
